// Generated by CoffeeScript 1.6.2
module.exports = function(compound) {
  var Bookmark, all;

  Bookmark = compound.models.Bookmark;
  all = function(doc) {
    return emit(doc.title, doc);
  };
  return Bookmark.defineRequest("all", all, function(err) {
    if (err) {
      compound.logger.write("Bookmark.All requests, cannot be created");
      return compound.logger.write(err);
    }
  });
};
