// Generated by CoffeeScript 1.6.2
module.exports = function(compound) {
  var app, express;

  express = require('express');
  app = compound.app;
  return app.configure(function() {
    app.enable('coffee');
    app.use(express["static"](app.root + '/client/public', {
      maxAge: 86400000
    }));
    app.use(express.bodyParser({
      keepExtensions: true
    }));
    app.use(express.methodOverride());
    return app.use(app.router);
  });
};
