// Generated by CoffeeScript 1.6.2
exports.routes = function(map) {
  map.get('bookmarks', 'bookmarks#all');
  map.post('bookmarks', 'bookmarks#create');
  return map.del('bookmarks/:id', 'bookmarks#destroy');
};
